// Copyright (c) 2026, Antoine Duval
// This file is part of a source-visible project.
// See LICENSE for terms. Unauthorized use is prohibited.

//#region Imports

import { Injectable } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';

//#endregion

@Injectable({
  providedIn: 'root'
})
export class GlobalService {
  //#region Attributes

  /** Express server port, randomly generated by the server when the program is launched. */
  public serverPort: number = 0;

  /** User's operating system. */
  public os?: NodeJS.Platform;

  /** Indicates whether the application is running in developer mode. */
  public devMode: boolean = false;

  /** Block the entire interface under a loading display. */
  public loading: string | undefined = undefined;

  /** URL to access the EBP Discord server. */
  public readonly discordServerURL: string = 'https://discord.gg/tAHAc9q3aX';

  /** Holds an optional list of user IDs that are part of the beta program. */
  public betaUsers: number[] | undefined;

  //#endregion

  constructor(private readonly translateService: TranslateService) {}

  //#region Functions

  /**
   * URL to access the EBP website.
   */
  public get webSiteURL(): string {
    return `https://evabattleplan.com/${this.translateService.currentLang}`;
  }

  /**
   * Generates a random integer between the specified minimum and maximum values, inclusive.
   * @param min Minimum value (inclusive).
   * @param max Maximum value (inclusive).
   * @returns A random integer between min and max.
   */
  public static random(min: number, max: number): number {
    return Math.floor(Math.random() * (max - min + 1) + min);
  }

  //#endregion
}
